### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by mikenorgate** [alechenninger/roger#1]
Is it possible to get a more permissive license on this? I would like to use a large portion of this (or at least the ideas) in a commercial project I'm working on, however my employer is not going to allow licensing our software under GPL.

**Comment by alechenninger** [comment]
Yeah I debated that. I'll switch it up.

**Comment by alechenninger** [comment]
MIT work for you?

**Comment by mikenorgate** [comment]
MIT would be great, thanks

**Comment by alechenninger** [comment]
@mikenorgate Enjoy. Would love to hear how using this works out for you or if you find or research any improvements.
